package contracts

const (
	AdapterModeEvaluationPacketSchema = "cautilus.adapter_mode_evaluation.v1"
	BehaviorIntentSchema              = "cautilus.behavior_intent.v1"
	ChatbotNormalizationInputsSchema  = "cautilus.chatbot_normalization_inputs.v1"
	CompareArtifactSchema             = "cautilus.compare_artifact.v1"
	DraftScenarioSchema               = "cautilus.scenario.v1"
	EvidenceBundleInputsSchema        = "cautilus.evidence_bundle_inputs.v1"
	EvidenceBundleSchema              = "cautilus.evidence_bundle.v1"
	OptimizeInputsSchema              = "cautilus.optimize_inputs.v1"
	OptimizeProposalSchema            = "cautilus.optimize_proposal.v1"
	OptimizeSearchInputsSchema        = "cautilus.optimize_search_inputs.v1"
	OptimizeSearchResultSchema        = "cautilus.optimize_search_result.v1"
	RevisionArtifactSchema            = "cautilus.revision_artifact.v1"
	ReportInputsSchema                = "cautilus.report_inputs.v1"
	ReportPacketSchema                = "cautilus.report_packet.v2"
	ReviewPacketSchema                = "cautilus.review_packet.v1"
	ReviewPromptInputsSchema          = "cautilus.review_prompt_inputs.v1"
	ReviewSummarySchema               = "cautilus.review_summary.v1"
	ReviewVariantResultSchema         = "cautilus.review_variant_result.v1"
	ScenarioBaselineCacheSchema       = "cautilus.scenario_baseline_cache.v1"
	ScenarioHistorySchema             = "cautilus.scenario_history.v1"
	ScenarioProfileSchema             = "cautilus.scenario_profile.v1"
	ScenarioProposalInputsSchema      = "cautilus.scenario_proposal_inputs.v1"
	ScenarioProposalsSchema           = "cautilus.scenario_proposals.v1"
	ScenarioResultsSchema             = "cautilus.scenario_results.v1"
	ScenarioTelemetrySummarySchema    = "cautilus.scenario_telemetry_summary.v1"
	SkillNormalizationInputsSchema    = "cautilus.skill_normalization_inputs.v1"
	WorkspaceRunManifestSchema        = "cautilus.workspace_run_manifest.v1"
)
